# Generated by Django 5.2.17 on 2026-08-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=120)),
                ('duration_minutes', models.IntegerField()),
                ('rating', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended')], default='RESERVED', max_length=20)),
                ('show_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='cine.show')),
            ],
        ),
    ]
